### ISSUE TITLE
我访问不了你的博客

### ISSUE THREAD

**Issue by ubuntu2204** [asjqkkkk/flutter-blog#2]
https://oldchen.top/flutter-blog/#/访问不了

**Comment by asjqkkkk** [comment]
> [https://oldchen.top/flutter-blog/#/访问不了](https://oldchen.top/flutter-blog/#/%E8%AE%BF%E9%97%AE%E4%B8%8D%E4%BA%86)

因为是在github page上面搭建的博客，所以可能不挂梯子的话会非常慢。

**Comment by asjqkkkk** [comment]
😂可能你需要准备一个梯子，后面我会考虑怎么去进行加速的

**Comment by asjqkkkk** [comment]
没有挂梯子的话,可以通过这个网址访问:
http://oldben.gitee.io/flutter-blog/#/homePage
是用码云搭建的page服务,蛮快的😂
