### ISSUE TITLE
Web compilation error

### ISSUE THREAD

**Issue by fengwang** [asjqkkkk/flutter-blog#3]
`flutter build web` gives the following errors:

> Running "flutter pub get" in flutter_blog...                        0.4s
> Target dart2js failed: Exception: lib/config/app_routers.dart:4:1:      
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
> import 'package:flutter_modular/flutter_modular.dart';
> ^^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/modular_base.dart:4:1:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
> import 'package:flutter_modular/flutter_modular.dart';
> ^^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/interfaces/child_module.dart:2:1:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
> import 'package:flutter_modular/flutter_modular.dart';
> ^^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/widgets/module_widget.dart:2:1:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
> import 'package:flutter_modular/flutter_modular.dart';
> ^^^^^^
> lib/config/app_routers.dart:12:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router(homePage, child: (_, args) => HomePage()),
>         ^^^^^^
> lib/config/app_routers.dart:13:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router(tagPage, child: (_, args) => TagPage()),
>         ^^^^^^
> lib/config/app_routers.dart:14:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router(archivePage, child: (_, args) => ArchivePage()),
>         ^^^^^^
> lib/config/app_routers.dart:15:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router(linkPage, child: (_, args) => FriendLinkPage()),
>         ^^^^^^
> lib/config/app_routers.dart:16:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router(aboutPage, child: (_, args) => AboutPage()),
>         ^^^^^^
> lib/config/app_routers.dart:17:9:
> Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:flutter_modular/src/routers/router.dart'.
>         Router("$articlePage/:name",
>         ^^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/modular_base.dart:75:64:
> Error: The getter 'child' isn't defined for the class 'Object'.
>  - 'Object' is from 'dart:core'.
>     for (var router in module.routers.where((router) => router.child != null)) {
>                                                                ^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/modular_base.dart:276:19:
> Error: The getter 'routerName' isn't defined for the class 'Object'.
>  - 'Object' is from 'dart:core'.
>           preview.routerName.contains('/:') == actual.routerName.contains('/:');
>                   ^^^^^^^^^^
> ../../../.pub-cache/hosted/pub.dartlang.org/flutter_modular-0.5.6/lib/src/modular_base.dart:276:55:
> Error: The getter 'routerName' isn't defined for the class 'Object'.
>  - 'Object' is from 'dart:core'.
>           preview.routerName.contains('/:') == actual.routerName.contains('/:');
>                                                       ^^^^^^^^^^
> lib/widgets/web_bar.dart:60:19:
> Error: No named parameter with the name 'colors'.
>                   colors: Colors.blueGrey,
>                   ^^^^^^
> /opt/flutter/packages/flutter/lib/src/material/flutter_logo.dart:24:9:
> Info: Found this candidate, but the arguments don't match.
>   const FlutterLogo({
>         ^^^^^^^^^^^
> Error: Compilation failed.
> 
> 
> Compiling lib/main.dart for the Web...                              8.6s
> Exception: Failed to compile application for the Web.

My Enviroment:

```
flutter doctor -v
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.0.pre at /opt/flutter
    • Framework revision a27c242b0e (8 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.1
    • cmake version 3.18.2
    • ninja version 1.10.1
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Chromium 85.0.4183.102 Arch Linux

• No issues found!
```

**Comment by asjqkkkk** [comment]
Hi, change this repo to `dev` channel, this issue will be solved

**Comment by fengwang** [comment]
> Hi, change this repo to `dev` channel, this issue will be solved

Exactly. Many Thanks.
