### ISSUE TITLE
视频页卡死

### ISSUE THREAD

**Issue by kuro7766** [asjqkkkk/flutter-blog#5]
如题，https://oldben.gitee.io/flutter-blog/#/articlePage/Daily%20English%20Dictation

**Comment by asjqkkkk** [comment]
这个应该和用了youtube显示插件有关系，可能需要等后续的更新

**Comment by kuro7766** [comment]
感觉flutter写markdown还是很蛋疼，我已经选择用了iframe了，效果还凑合
http://kuroweb.cf/ci/blog/web/#/entrance?user=a

**Comment by asjqkkkk** [comment]
> 感觉flutter写markdown还是很蛋疼，我已经选择用了iframe了，效果还凑合
> http://kuroweb.cf/ci/blog/web/#/entrance?user=a

看了一下，效果也可以😄
不过这个可以支持TOC功能吗

**Comment by kuro7766** [comment]
不支持，我这个是做课设的。老师主要看个UI效果。

综合考虑了一下，还是不太敢用flutter。

**Comment by asjqkkkk** [comment]
> 不支持，我这个是做课设的。老师主要看个UI效果。
> 
> 综合考虑了一下，还是不太敢用flutter。

😄UI效果的话还是要有设计的好一些，等我把博客翻新你就可以看到最新的效果了

**Comment by kuro7766** [comment]
toc的话在iframe实现一个小窗口应该可行，毕竟生态丰富。

就是不能出来到flutter组件这边。

而且iframe会把flutter canvas挡住(下层canvas捕获不了点击事件)，不能重叠复杂UI。

**Comment by kuro7766** [comment]
> > 不支持，我这个是做课设的。老师主要看个UI效果。
> > 综合考虑了一下，还是不太敢用flutter。
> 
> 😄UI效果的话还是要有设计的好一些，等我把博客翻新你就可以看到最新的效果了

好的，期待效果

**Comment by asjqkkkk** [comment]
> > > 不支持，我这个是做课设的。老师主要看个UI效果。
> > > 综合考虑了一下，还是不太敢用flutter。
> > 
> > 
> > 😄UI效果的话还是要有设计的好一些，等我把博客翻新你就可以看到最新的效果了
> 
> 好的，期待效果

Hi, 新博客在这里：oldchen.top
感兴趣的话可以看一下，目前完成了一部分

**Comment by kuro7766** [comment]
太炫了，学到了学到了

**Comment by kuro7766** [comment]
大佬开源吗

还有这个音乐选择器好像有点问题
![image](https://user-images.githubusercontent.com/49401947/116889513-3c642a00-ac5f-11eb-8f3e-b3436feec168.png)

**Comment by asjqkkkk** [comment]
> 大佬开源吗
> 
> 还有这个音乐选择器好像有点问题
> ![image](https://user-images.githubusercontent.com/49401947/116889513-3c642a00-ac5f-11eb-8f3e-b3436feec168.png)

目前确实会有一些小问题😂后续等整体上初步功能完成后会开源的

**Comment by asjqkkkk** [comment]
已开源
